#!/bin/bash
# Interface to the Arch Linux ABS (Arch Build System)
# absent is to the ABS what aurget, packer, etc. are to the AUR.
# 2010-2014, Johannes Langøy. Public domain.

searchdirs=("/var/abs/core" "/var/abs/extra" "/var/abs/community")
builddir="/tmp/absent-$USER"

# You can override the above variables in this config file.
if [[ -f ~/.absentrc ]]; then
    source ~/.absentrc
fi

leader=$'\e[1;34m::\e[0m'

function lecho {
    echo "$leader $*"
}

function ask {
    echo -n "$leader $* [Y/n] "
    read -r
    case "$REPLY" in
        (''|[yY]*) return 0 ;;
        (*) return 1 ;;
    esac
}

function usage {
    echo "absent -- an ABS helper
\$searchdirs: (${searchdirs[@]})
\$builddir: \"$builddir\"
absent -S [name..]: build and install
absent -G [name..]: copy to the current directory
absent [string]: select from packages whose name matches the given string"
}

function find-copy {
    name="$1"
    dest="$2"
    unset match
    for dir in "${searchdirs[@]}"; do
        if [[ -d "$dir/$name/" && -f "$dir/$name/PKGBUILD" ]]; then
            match="$dir/$name/"
            break
        fi
    done
    if [[ -z "$match" ]]; then
        lecho "No match found for $name in \$searchdirs (${searchdirs[@]})."
        exit 1
    fi
    lecho "$name copied from $dir."
    cp -r "$match" "$dest"
    match="$dest/$(basename $match)"
}

function interactive {
    if ask "Edit PKGBUILD?"; then
        ${EDITOR:-vi} PKGBUILD
    fi
    unset install
    source PKGBUILD
    if [[ -n "$install" ]] && ask "Edit $install?"; then
        ${EDITOR:-vi} $install
    fi
}

if ! mkdir -p "$builddir"; then
    lecho "Fix your \$builddir."
    exit 1
fi

case "$1" in
("")
    usage
    exit 1
    ;;
(-*)
    flag="$1"
    shift
    case "$flag" in
    (-S)
        for i in "$@"; do
            find-copy "$i" "$builddir"
            cd "$match"
            interactive
            makepkg -fsci
            cd ..
        done
        ;;
    (-G)
        for i in "$@"; do
            find-copy "$i" .
        done
        ;;
    (*)
        usage
        exit
        ;;
    esac
    ;;
(*)
    select match in $(find "${searchdirs[@]}" -maxdepth 1 -type d -name "*$**"); do
        cp -r "$match" "$builddir"
        cd "$builddir/$(basename $match)"
        interactive
        makepkg -fsci
        break
    done
    ;;
esac
